// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Updater.ApiService.Database;

#nullable disable

namespace Updater.ApiService.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251210115609_SchemaChangeAndRefactor")]
    partial class SchemaChangeAndRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Updater.ApiService.Database.Models.Binary", b =>
                {
                    b.Property<Guid>("SoftwareId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RawBinary")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("SoftwareId");

                    b.ToTable("Binarys");
                });

            modelBuilder.Entity("Updater.ApiService.Database.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("CurrentSoftwareId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PendingSoftwareId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CurrentSoftwareId");

                    b.HasIndex("GroupId");

                    b.HasIndex("PendingSoftwareId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Updater.ApiService.Database.Models.DeviceActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceActivities");
                });

            modelBuilder.Entity("Updater.ApiService.Database.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("HMACKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetSoftwareId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("UseHMAC")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TargetSoftwareId");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Updater.ApiService.Database.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Updater.ApiService.Database.Models.Software", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("VerMajor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Softwares");
                });

            modelBuilder.Entity("Updater.ApiService.Database.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Updater.ApiService.Database.Models.UserProject", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("UserProjects");
                });

            modelBuilder.Entity("Updater.ApiService.Database.Models.Binary", b =>
                {
                    b.HasOne("Updater.ApiService.Database.Models.Software", "Software")
                        .WithOne("Binary")
                        .HasForeignKey("Updater.ApiService.Database.Models.Binary", "SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Software");
                });

            modelBuilder.Entity("Updater.ApiService.Database.Models.Device", b =>
                {
                    b.HasOne("Updater.ApiService.Database.Models.Software", "CurrentSoftware")
                        .WithMany("DevicesUsingThisSoftware")
                        .HasForeignKey("CurrentSoftwareId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Updater.ApiService.Database.Models.Group", "Group")
                        .WithMany("Devices")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Updater.ApiService.Database.Models.Software", "PendingSoftware")
                        .WithMany()
                        .HasForeignKey("PendingSoftwareId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentSoftware");

                    b.Navigation("Group");

                    b.Navigation("PendingSoftware");
                });

            modelBuilder.Entity("Updater.ApiService.Database.Models.DeviceActivity", b =>
                {
                    b.HasOne("Updater.ApiService.Database.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Updater.ApiService.Database.Models.Group", b =>
                {
                    b.HasOne("Updater.ApiService.Database.Models.Project", "Project")
                        .WithMany("Groups")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Updater.ApiService.Database.Models.Software", "TargetSoftware")
                        .WithMany("GroupsUsingThisSoftware")
                        .HasForeignKey("TargetSoftwareId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("TargetSoftware");
                });

            modelBuilder.Entity("Updater.ApiService.Database.Models.Software", b =>
                {
                    b.HasOne("Updater.ApiService.Database.Models.Group", "Group")
                        .WithMany("Softwares")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Updater.ApiService.Database.Models.User", "Uploader")
                        .WithMany("UploadedSoftwares")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Updater.ApiService.Database.Models.UserProject", b =>
                {
                    b.HasOne("Updater.ApiService.Database.Models.Project", "Project")
                        .WithMany("UserProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Updater.ApiService.Database.Models.User", "User")
                        .WithMany("UserProjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Updater.ApiService.Database.Models.Group", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Softwares");
                });

            modelBuilder.Entity("Updater.ApiService.Database.Models.Project", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("UserProjects");
                });

            modelBuilder.Entity("Updater.ApiService.Database.Models.Software", b =>
                {
                    b.Navigation("Binary");

                    b.Navigation("DevicesUsingThisSoftware");

                    b.Navigation("GroupsUsingThisSoftware");
                });

            modelBuilder.Entity("Updater.ApiService.Database.Models.User", b =>
                {
                    b.Navigation("UploadedSoftwares");

                    b.Navigation("UserProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
